name: AdvancedKits
main: AdvancedKits\Main
version: 1.0.0
api: [3.0.0]
author: PlatinumGamesDevs
authors: luca28pet, PlatinumGamesDevs
softdepend: [""]
description: "KitChestPMMP By PlatinumGamesDevs And Server"
commands:
 kit:
  description: KitChestPMMP By PlatinumGamesDevs And Server
  usage: "/kit <Kit Name>"
  permission: advancedkits.command
  aliases: [kits, kitlist]
permissions:
 advancedkits.command:
  description: "allows the player to use /kit command"
  default: true
