name: AdvancedKits
main: AdvancedKits\Main
version: 1.0.0
api: [4.0.0]
author: PlatinumGamesDevs
softdepend: [""]
description: "KitChestPMMP By PlatinumGamesDevs And Server"
commands:
 kit:
  description: "KitChestPMMP By PlatinumGamesDevs And Server"
  usage: "/kit <kit name>"
  permission: advancedkits.command
  aliases: [kits, kitlist]
permissions:
 advancedkits.command:
  description: "allows the player to use /kit command"
  default: true
